name: Generate Snake

on:
  schedule: # Executa a cada 12 horas
    - cron: "0 */12 * * *"
  workflow_dispatch: # Permite executar manualmente o workflow

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout do repositório
      - name: Checkout
        uses: actions/checkout@v2

      # Gera a animação da cobrinha
      - name: Generate Snake Animation
        uses: Platane/snk@master
        with:
          github_user_name: Ceeezinh0 # Substitua pelo seu nome de usuário do GitHub
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Publica a imagem gerada na branch output
      - name: Publish Snake Animation
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
